default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Furukawa
  password:

development:
  <<: *default
  database: portfolio_development
  host: localhost

test:
  <<: *default
  database: portfolio_test